# ========================================
# application-prod.properties (perfil PROD)
# ========================================
# Activar: mvn spring-boot:run -Dspring-boot.run.profiles=prod

app.message=Hola desde PERFIL PRODUCCION
app.info.environment=production
app.datasource.url=jdbc:postgresql://db-server:5432/proddb
app.datasource.username=app_user
app.datasource.driver-class-name=org.postgresql.Driver
app.datasource.pool.max-size=50
app.datasource.pool.min-idle=10
app.datasource.pool.timeout-ms=10000
