# ========================================
# application-dev.properties (perfil DEV)
# ========================================
# Activar: mvn spring-boot:run -Dspring-boot.run.profiles=dev

app.message=Hola desde PERFIL DEV
app.info.environment=development
app.datasource.url=jdbc:h2:mem:devdb
app.datasource.pool.max-size=5
app.datasource.pool.min-idle=1
